
// Mock data, in a real app this would come from an API
export const mockTramitesData = {
  '12022': { 
    id: "12022",
    hasWarning: true,
    solicitante: "LONGPORT AVIATION SECURITY, S.R.L",
    para: "WILKENIA EDOUARD FILMONOR",
    asignadoA: "MDPP",
    categoria: "INSPECTOR DE SEGURIDAD PRIVADA DE LA AVIACIÓN CIVIL",
    proceso: "Certificación del personal de seguridad privada de la aviación civil",
    referencia: "40236591208",
    subproceso: "Recepción formulario de datos personales",
    ejecutores: [ "AMAURIS MERCEDES CASTILLO", "KENDY ALEJANDRO QUALEY TAVERAS", "MICHEL ALT. MARIANO QUEZADA" ],
    validadores: [ "ROBINSON ACOSTA PEÑA", "WASCAR BIENVENIDO CASTRO GARCIA", "YISSEL MARCIAL DE JESUS" ],
    ingreso: "01/08/2024 10:00 AM",
    vence: "02/08/2024 10:00 AM",
    progress: 20,
    infoTramite: {
        fechaNacimiento: '1995-02-15',
        nacionalidad: 'Dominicana',
    },
    status: "Discrepancias"
  },
  'E-73482': {
    id: 'E-73482',
    solicitante: "Sample Company",
    proceso: 'Certificación de Seguridad para Carga',
    producto: 'Certificado de Seguridad de Carga Aérea',
    tipoTramite: 'EMPRESA' as const,
    categoriaEmpresaId: '3',
    equiposSeguridad: ['rayos_x', 'escaner'],
    aeropuertos: ['mdsd', 'mdpc'],
    serviciosSeguridad: ['seguridad_carga', 'inspeccion_carga'],
    requeridoCertificacion: true,
    requeridoModificacionPrograma: false,
    descripcionModificacion: '',
    documentosRequeridos: [
      {
        id: 'doc1',
        descripcion: 'Copia del RNC actualizado.',
        nota: 'Debe estar vigente.',
        departamentos: ['d1'],
        obligatorio: true,
      },
      {
        id: 'doc2',
        descripcion: 'Certificación de la Cámara de Comercio.',
        nota: '',
        departamentos: ['d1', 'd4'],
        obligatorio: true,
      }
    ],
  },
  'E-58291': {
    id: 'E-58291',
    solicitante: "Sample Airline",
    proceso: 'Aprobación Programa de Seguridad de Aerolínea',
    producto: 'Programa de Seguridad Aprobado',
    tipoTramite: 'EMPRESA' as const,
    categoriaEmpresaId: '1',
    equiposSeguridad: [],
    aeropuertos: ['mdsd', 'mdst', 'mdpc', 'mdlr', 'mdpp', 'mdcy', 'mdbh', 'mdjb', 'mdab'],
    serviciosSeguridad: ['seguridad_aeronave'],
    requeridoCertificacion: false,
    requeridoModificacionPrograma: true,
    descripcionModificacion: 'Actualización de procedimientos de inspección de pasajeros y equipaje de mano.',
    documentosRequeridos: [
        {
            id: 'doc5',
            descripcion: 'Carta de solicitud de aprobación del programa.',
            nota: '',
            departamentos: ['d1'],
            obligatorio: true,
        },
        {
            id: 'doc6',
            descripcion: 'Copia del programa de seguridad propuesto.',
            nota: 'En formato digital (PDF).',
            departamentos: ['d1', 'd2'],
            obligatorio: true,
        }
    ],
  },
  'P-12345': {
    id: 'P-12345',
    solicitante: "Security Services Inc.",
    proceso: 'Certificación del personal de seguridad privada de la aviación civil',
    producto: 'Certificación y Re-certificación del Personal de Seguridad Privada de la Aviación Civil',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: ['mdsd', 'mdst', 'mdpc', 'mdlr', 'mdpp', 'mdcy', 'mdbh', 'mdjb', 'mdab'],
    categoriaPersonal: ['inspector_privada'],
    categoriaCia: ['serv_privado'],
    poseePrograma: 'no',
    documentosRequeridos: [
      { id: 'doc-p-cert-1', descripcion: 'Listado del personal que ha culminado y aprobado la Instrucción Periódica, impartida por instructores certificados por el CESAC.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-cert-2', descripcion: 'Copia de Cédula de Identidad.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-cert-3', descripcion: 'Copia del Carnet de identificación y acceso expedido del aeropuerto donde presta servicio.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-cert-4', descripcion: 'Copia del Reporte de las Calificaciones de la instrucción recibida (Teórica y Práctica), impartida por la Empresa, Firmado por un instructor debidamente certificado por el CESAC.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-cert-5', descripcion: 'Evaluación Médica (Admisional y audiometría) y Analíticas Médicas (Hemograma, Glicemia, Urea, Creatinina, VDRL, HBSAC y HVC).', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-cert-6', descripcion: 'Presentar comprobante de realización de la Prueba de Dopaje, por el CESAC.', departamentos: ['d1', 'd3'], obligatorio: true, nota: '' },
      { id: 'doc-p-cert-7', descripcion: 'Proceso de certificación: Evaluación Psicológica, Teórica, Práctica, Verificación de Antecedentes y Emisión de la Licencia.', nota: 'Costo: US$ 82.39 por persona, a pagar 24 horas antes.', departamentos: ['d1', 'd3'], obligatorio: true },
    ],
  },
  'P-23456': {
    id: 'P-23456',
    solicitante: "CESAC Internal",
    proceso: 'Re-Certificación del personal AVSEC del CESAC',
    producto: 'Re-certificación del Personal AVSEC del CESAC',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: ['mdsd', 'mdst', 'mdpc', 'mdlr', 'mdpp', 'mdcy', 'mdbh', 'mdjb', 'mdab'],
    categoriaPersonal: ['inspector_nacional', 'inspector_cat'],
    categoriaCia: ['cesac'],
    poseePrograma: 'si',
    documentosRequeridos: [
      { id: 'doc-p-recert-1', descripcion: 'Listado de personal que ha culminado y aprobado la Instrucción Inicial de la ESAC.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-recert-2', descripcion: 'Copia de Cédula de Identidad.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-recert-3', descripcion: 'Copia del diploma de la Instrucción y Certificación de los conocimientos adquiridos.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-recert-4', descripcion: 'Copia de Carnet de Identificación.', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-recert-5', descripcion: 'Evaluación Médica (Admisional y audiometría) y Analítica Médicas (Hemograma, Glicemia, Urea, Creatinina, VDRL, HBSAC y HVC).', departamentos: ['d1'], obligatorio: true, nota: '' },
      { id: 'doc-p-recert-6', descripcion: 'Presentar comprobante de realización de la Prueba de Dopaje, por el CESAC.', departamentos: ['d1', 'd3'], obligatorio: true, nota: '' },
      { id: 'doc-p-recert-7', descripcion: 'Proceso de Re-certificación: Evaluación Psicológica, Teórica, Práctica, Verificación de Antecedentes y Emisión de la Licencia.', nota: 'Costo: US$ 89.39 por persona, a pagar 24 horas antes.', departamentos: ['d1', 'd3'], obligatorio: true },
    ],
  },
  'P-34567': {
    id: 'P-34567',
    solicitante: "Security Services Inc.",
    proceso: 'Re-impresión de licencia por cambio de compañía',
    producto: 'Re-impresión de licencia por cambio de compañía del Personal de Seguridad Privada de la Aviación Civil',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: [],
    categoriaPersonal: [],
    categoriaCia: [],
    poseePrograma: 'no',
    documentosRequeridos: [],
  },
  'P-45678': {
    id: 'P-45678',
    solicitante: "CESAC Internal",
    proceso: 'Certificación del personal AVSEC del CESAC',
    producto: 'Certificación del Personal AVSEC del CESAC',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: [],
    categoriaPersonal: [],
    categoriaCia: [],
    poseePrograma: 'no',
    documentosRequeridos: [],
  },
  'P-56789': {
    id: 'P-56789',
    solicitante: "Security Services Inc.",
    proceso: 'Re-impresión de licencia por perdida o robo (Seguridad Privada)',
    producto: 'Re-impresión de licencia por perdida o robo del Personal de Seguridad Privada de la Aviación Civil',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: [],
    categoriaPersonal: [],
    categoriaCia: [],
    poseePrograma: 'no',
    documentosRequeridos: [],
  },
  'P-67890': {
    id: 'P-67890',
    solicitante: "Security Services Inc.",
    proceso: 'Re-impresión de licencia por deterioro (Seguridad Privada)',
    producto: 'Re-impresión de licencia por deterioro del Personal de Seguridad Privada de la Aviación Civil',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: [],
    categoriaPersonal: [],
    categoriaCia: [],
    poseePrograma: 'no',
    documentosRequeridos: [],
  },
  'P-78901': {
    id: 'P-78901',
    solicitante: "CESAC Internal",
    proceso: 'Re-impresión de licencia por perdida o robo (AVSEC)',
    producto: 'Re-impresión de licencia por perdida o robo del Personal AVSEC del CESAC',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: [],
    categoriaPersonal: [],
    categoriaCia: [],
    poseePrograma: 'no',
    documentosRequeridos: [],
  },
  'P-89012': {
    id: 'P-89012',
    solicitante: "CESAC Internal",
    proceso: 'Re-impresión de licencia por deterioro (AVSEC)',
    producto: 'Re-impresión de licencia por deterioro del Personal AVSEC del CESAC',
    tipoTramite: 'PERSONA' as const,
    aeropuertos: [],
    categoriaPersonal: [],
    categoriaCia: [],
    poseePrograma: 'no',
    documentosRequeridos: [],
  },
};

export const categoriasEmpresa = [
  { id: '1', nombre: 'EMPRESAS DE APROVISIONAMIENTO Y SUMINISTRO' },
  { id: '2', nombre: 'ARRENDATARIOS EN AEROPUERTO' },
  { id: '3', nombre: 'PROVEEDORES DE SERVICIOS PRIVADOS DE SEGURIDAD' },
];
export const equiposSeguridad = [
    { id: "camaras", label: "Cámaras" }, { id: "escaner", label: "Escáner" },
    { id: "rayos_x", label: "Máquina de Rayos X" }, { id: "detector_portatil", label: "Detector de Metal Portátil" },
    { id: "arco_detector", label: "Arco Detector de Metal" }, { id: "mmtd", label: "MMTD" },
];
export const aeropuertos = [
    { id: "mdsd", label: "MDSD" }, { id: "mdst", label: "MDST" }, { id: "mdpc", label: "MDPC" },
    { id: "mdbh", label: "MDBH" }, { id: "mdcy", label: "MDCY" }, { id: "mdjb", label: "MDJB" },
    { id: "mdlr", label: "MDLR" }, { id: "mdab", label: "MDAB" }, { id: "mdpp", label: "MDPP" },
];
export const serviciosSeguridad = [
    { id: 'seguridad_carga', label: 'Seguridad de la carga' },
    { id: 'escolta_pasajeros', label: 'Escolta de los pasajeros' },
    { id: 'control_seguridad', label: 'Control de seguridad en la zona de presentación' },
    { id: 'seguridad_aeronave', label: 'Seguridad de la aeronave' },
    { id: 'control_equipaje', label: 'Control de seguridad de equipaje de bodega' },
    { id: 'inspeccion_carga', label: 'Inspección de la carga en sus instalaciones' },
    { id: 'inspeccion_suministros', label: 'Inspección de suministros en sus instalaciones' },
];
export const categoriaPersonal = [
    {id: 'supervisor', label: 'SUPERVISOR AVSEC'}, {id: 'instructor', label: 'INSTRUCTOR AVSEC'},
    {id: 'gerente', label: 'GERENTE AVSEC'}, {id: 'manejador_k9', label: 'MANEJADOR K-9'},
    {id: 'inspector_nacional', label: 'INSPECTOR NACIONAL AVSEC'}, {id: 'inspector_cat', label: 'INSPECTOR AVSEC 1RA CAT'},
    {id: 'inspector_privada', label: 'INSPECTOR DE SEGURIDAD PRIVADA'},
];
export const categoriaCia = [
    {id: 'cesac', label: 'CESAC'}, {id: 'explotadores', label: 'EXPLOTADORES DE AERONAVE'},
    {id: 'serv_privado', label: 'PROVEEDORES DE SERV. PRIVADO'}, {id: 'aprov_aeronave', label: 'APROVICIONAMIENTO DE AERONAVE (CATERING)'},
];
export const departamentos = [
    {id: 'd1', label: 'ACREDITACIÓN'}, {id: 'd2', label: 'TECNOLOGÍA'},
    {id: 'd3', label: 'TESORERIA'}, {id: 'd4', label: 'ASUNTOS INTERNOS'},
];
