// prisma/seeds/002_apps.ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export async function seedApps() {
  console.log('🌱 Seeding apps...')

  const apps = [
    {
      id: 'SGU',
      nombre: 'Sistema Gestión Usuario',
      descripcion: 'Plataforma centralizada para la administración de identidades y accesos. Permite la creación, modificación y eliminación de usuarios, así como la asignación de roles y permisos a través de todas las aplicaciones integradas al PGA.',
      activa: true,
      version: '2.5.1',
      lastUpdate: new Date('2024-07-28'),
      lastAudit: new Date('2024-06-15'),
      auditorId: 1, // Ana García (simulado)
      clientId: 'SGU_CLIENT_001',
      code: 'SGU_CODE_XYZ',
      urlDestino: 'https://sgu.cesac.mil.do',
      redirectUrl: 'https://sgu.cesac.mil.do/auth/callback',
      assignedDevId: 2, // Carlos Martinez (simulado)
      backendDevId: 3,  // Luisa Fernandez (simulado)
      frontendDevId: 4, // Kendy Qualey (simulado)
      users72h: 152,
      totalUsers: 590,
    },
    {
      id: 'SCU',
      nombre: 'Sistema Carnet Unico',
      descripcion: 'Herramienta dedicada a la emisión, gestión y renovación de carnets de identificación únicos para todo el personal. Centraliza la información y agiliza los procesos de acreditación física en los aeropuertos.',
      activa: true,
      version: '1.8.0',
      lastUpdate: new Date('2024-05-10'),
      lastAudit: new Date('2024-04-20'),
      auditorId: 1,
      clientId: 'SCU_CLIENT_002',
      code: 'SCU_CODE_ABC',
      urlDestino: 'https://scu.cesac.mil.do',
      redirectUrl: 'https://scu.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 89,
      totalUsers: 980,
    },
    {
      id: 'SDP',
      nombre: 'Sistema de documentacion de poligrafia',
      descripcion: 'Plataforma segura para la gestión y archivo de toda la documentación relacionada con pruebas de polígrafo. Garantiza la confidencialidad y el acceso controlado a información sensible para el personal autorizado.',
      activa: true,
      version: '3.0.0',
      lastUpdate: new Date('2024-07-20'),
      lastAudit: new Date('2024-07-01'),
      auditorId: 1,
      clientId: 'SDP_CLIENT_003',
      code: 'SDP_CODE_123',
      urlDestino: 'https://sdp.cesac.mil.do',
      redirectUrl: 'https://sdp.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 34,
      totalUsers: 450,
    },
    {
      id: 'RRHH',
      nombre: 'Sistema de Reclutamiento de la Direccion de Recursos humanos',
      descripcion: 'Solución integral para la gestión de Recursos Humanos, optimizando el ciclo de vida del empleado desde el reclutamiento y la selección hasta la gestión de su perfil profesional y capacitaciones.',
      activa: true,
      version: '2.1.0',
      lastUpdate: new Date('2024-07-01'),
      lastAudit: new Date('2024-05-10'),
      auditorId: 1,
      clientId: 'RRHH_CLIENT_004',
      code: 'RRHH_CODE_456',
      urlDestino: 'https://rrhh.cesac.mil.do',
      redirectUrl: 'https://rrhh.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 120,
      totalUsers: 800,
    },
    {
      id: 'SIARED',
      nombre: 'Sistema Automatizado de Recepción de Documentos de Cursos',
      descripcion: 'Sistema Automatizado de Recepción de Documentos de Cursos. Facilita la inscripción, seguimiento y certificación de los cursos de capacitación, automatizando la entrega y validación de la documentación requerida.',
      activa: true,
      version: '1.2.5',
      lastUpdate: new Date('2024-06-15'),
      lastAudit: new Date('2024-05-01'),
      auditorId: 1,
      clientId: 'SIARED_CLIENT_005',
      code: 'SIARED_CODE_789',
      urlDestino: 'https://siared.cesac.mil.do',
      redirectUrl: 'https://siared.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 75,
      totalUsers: 600,
    },
    {
      id: 'SGAC',
      nombre: 'Sistema de Gestión y Administración de Correspondencia',
      descripcion: 'Herramienta para la gestión y administración de correspondencia interna y externa del CESAC. Digitaliza el flujo de documentos, mejora el seguimiento y reduce los tiempos de respuesta.',
      activa: true,
      version: '4.0.0',
      lastUpdate: new Date('2024-07-25'),
      lastAudit: new Date('2024-06-30'),
      auditorId: 1,
      clientId: 'SGAC_CLIENT_006',
      code: 'SGAC_CODE_101',
      urlDestino: 'https://sgac.cesac.mil.do',
      redirectUrl: 'https://sgac.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 200,
      totalUsers: 1500,
    },
    {
      id: 'SCC',
      nombre: 'Sistema de Control de Calidad',
      descripcion: 'Sistema para la Gestión de Documentos de Control de Calidad. Permite estandarizar procesos, realizar auditorías y dar seguimiento a no conformidades, asegurando el cumplimiento de los más altos estándares de calidad.',
      activa: false,
      version: '1.5.0',
      lastUpdate: new Date('2023-12-01'),
      lastAudit: new Date('2023-11-15'),
      auditorId: 1,
      clientId: 'SCC_CLIENT_007',
      code: 'SCC_CODE_202',
      urlDestino: 'https://scc.cesac.mil.do',
      redirectUrl: 'https://scc.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 0,
      totalUsers: 50,
    },
    {
      id: 'SCF',
      nombre: 'Sistema de Control de Flotas',
      descripcion: 'Plataforma para la administración y monitoreo en tiempo real de la flota vehicular del CESAC. Optimiza rutas, controla el consumo de combustible y gestiona el mantenimiento preventivo para garantizar la operatividad.',
      activa: true,
      version: '2.2.0',
      lastUpdate: new Date('2024-07-18'),
      lastAudit: new Date('2024-06-25'),
      auditorId: 1,
      clientId: 'SCF_CLIENT_008',
      code: 'SCF_CODE_303',
      urlDestino: 'https://scf.cesac.mil.do',
      redirectUrl: 'https://scf.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 45,
      totalUsers: 300,
    },
    {
      id: 'Laboratorio',
      nombre: 'Sistema de Gestión de Muestras para Laboratorio',
      descripcion: 'Controla el flujo de muestras, desde la recepción hasta el análisis y la emisión de resultados, asegurando trazabilidad y fiabilidad en los procesos de laboratorio.',
      activa: false,
      version: '1.0.0',
      lastUpdate: new Date('2023-10-10'),
      lastAudit: new Date('2023-09-20'),
      auditorId: 1,
      clientId: 'LAB_CLIENT_009',
      code: 'LAB_CODE_404',
      urlDestino: 'https://lab.cesac.mil.do',
      redirectUrl: 'https://lab.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 0,
      totalUsers: 30,
    },
    {
      id: 'SGLS',
      nombre: 'Sistema Gestión Lista Servicios Aeropuertos',
      descripcion: 'Aplicación para la gestión centralizada de la lista de servicios disponibles en los diferentes aeropuertos. Facilita la consulta y actualización de la oferta de servicios para aerolíneas y personal.',
      activa: true,
      version: '1.0.0',
      lastUpdate: new Date('2024-03-01'),
      lastAudit: new Date('2024-02-10'),
      auditorId: 1,
      clientId: 'SGLS_CLIENT_010',
      code: 'SGLS_CODE_505',
      urlDestino: 'https://sgls.cesac.mil.do',
      redirectUrl: 'https://sgls.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 60,
      totalUsers: 400,
    },
    {
      id: 'SGA - CESAC',
      nombre: 'Sistema Gestión de Acreditacion (Nube)',
      descripcion: 'La versión cloud del sistema de acreditación, diseñada para ofrecer alta disponibilidad, escalabilidad y acceso seguro desde cualquier ubicación para la gestión de trámites.',
      activa: true,
      version: '1.0.0-Nube',
      lastUpdate: new Date('2024-07-30'),
      lastAudit: new Date('2024-07-15'),
      auditorId: 1,
      clientId: 'SGA_NUBE_CLIENT_015',
      code: 'SGA_NUBE_CODE_111',
      urlDestino: 'https://sga-nube.cesac.mil.do',
      redirectUrl: 'https://sga-nube.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 300,
      totalUsers: 2000,
    },
    {
      id: 'MA - CESAC',
      nombre: 'Modulo de Acreditacion',
      descripcion: 'Módulo principal de Acreditación. Es el núcleo operativo para la gestión de trámites, certificaciones y validaciones de personal y empresas, integrando todos los procesos de seguridad aeroportuaria.',
      activa: true,
      version: '3.1.2',
      lastUpdate: new Date('2024-07-12'),
      lastAudit: new Date('2024-06-20'),
      auditorId: 1,
      clientId: 'MA_CLIENT_016',
      code: 'MA_CODE_222',
      urlDestino: 'https://ma.cesac.mil.do',
      redirectUrl: 'https://ma.cesac.mil.do/auth/callback',
      assignedDevId: 2,
      backendDevId: 3,
      frontendDevId: 4,
      users72h: 180,
      totalUsers: 1800,
    },
  ]

  for (const app of apps) {
    await prisma.app.upsert({
      where: { id: app.id },
      update: {},
      create: app,
    })
  }

  console.log('✅ Apps seeded successfully')
}