
"use client";

import {
    Users,
    BadgeInfo,
    FileScan,
    UserPlus,
    BookCopy,
    Mail,
    ClipboardCheck,
    Truck,
    FlaskConical,
    Plane,
    BarChart2,
    Network,
    Code2,
    LayoutGrid,
    LifeBuoy,
    Settings,
} from "lucide-react";

export const initialApps = [
    {
        id: 'SGU',
        logo: Users,
        nombre: 'Sistema Gestión Usuario',
        descripcion: 'Plataforma centralizada para la administración de identidades y accesos. Permite la creación, modificación y eliminación de usuarios, así como la asignación de roles y permisos a través de todas las aplicaciones integradas al PGA.',
        activa: true,
        version: '2.5.1',
        lastUpdate: '2024-07-28',
        lastAudit: '2024-06-15',
        auditor: 'Ana García',
        incidents: [{ type: 'Advertencia', count: 3, description: 'Intentos de acceso fallidos.' }],
        clientId: 'SGU_CLIENT_001',
        code: 'SGU_CODE_XYZ',
        urlDestino: 'https://sgu.cesac.mil.do',
        redirectUrl: 'https://sgu.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 152,
        totalUsers: 590,
        technicalDetails: {
            stack: ['Next.js (React)', 'Node.js (Express)', 'TypeScript'],
            architecture: 'Microservicios',
            database: 'PostgreSQL 14',
            cicd: ['GitHub Actions', 'Docker', 'Kubernetes (GKE)'],
            repository: 'github.com/cesac/sgu-main',
        },
    },
    {
        id: 'SCU',
        logo: BadgeInfo,
        nombre: 'Sistema Carnet Unico',
        descripcion: 'Herramienta dedicada a la emisión, gestión y renovación de carnets de identificación únicos para todo el personal. Centraliza la información y agiliza los procesos de acreditación física en los aeropuertos.',
        activa: true,
        version: '1.8.0',
        lastUpdate: '2024-05-10',
        lastAudit: '2024-04-20',
        auditor: 'Juan Perez',
        incidents: [],
        clientId: 'SCU_CLIENT_002',
        code: 'SCU_CODE_ABC',
        urlDestino: 'https://scu.cesac.mil.do',
        redirectUrl: 'https://scu.cesac.mil.do/auth/callback',
        assignedDev: 'Maria Rodriguez',
        backendDev: 'Jorge Diaz',
        frontendDev: 'Kendy Qualey',
        users72h: 89,
        totalUsers: 980,
        technicalDetails: {
            stack: ['React (Vite)', 'PHP (Laravel)', 'MySQL'],
            architecture: 'Monolito Modular',
            database: 'MySQL 8.0',
            cicd: ['Jenkins', 'Docker', 'On-Premise Server'],
            repository: 'github.com/cesac/scu-legacy',
        },
    },
    {
        id: 'SDP',
        logo: FileScan,
        nombre: 'Sistema de documentacion de poligrafia',
        descripcion: 'Plataforma segura para la gestión y archivo de toda la documentación relacionada con pruebas de polígrafo. Garantiza la confidencialidad y el acceso controlado a información sensible para el personal autorizado.',
        activa: true,
        version: '3.0.0',
        lastUpdate: '2024-07-20',
        lastAudit: '2024-07-01',
        auditor: 'Ana García',
        incidents: [{ type: 'Crítico', count: 1, description: 'Fuga de datos detectada y contenida.' }],
        clientId: 'SDP_CLIENT_003',
        code: 'SDP_CODE_123',
        urlDestino: 'https://sdp.cesac.mil.do',
        redirectUrl: 'https://sdp.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 34,
        totalUsers: 450,
        technicalDetails: {
            stack: ['Next.js', 'Python (FastAPI)', 'PostgreSQL'],
            architecture: 'Arquitectura Segura de Cero Confianza (Zero Trust)',
            database: 'PostgreSQL 15 con cifrado en reposo',
            cicd: ['GitHub Actions', 'Docker (con escaneo de vulnerabilidades)', 'Vault'],
            repository: 'github.com/cesac/sdp-secure-api',
        },
    },
    {
        id: 'RRHH',
        logo: UserPlus,
        nombre: 'Sistema de Reclutamiento de la Direccion de Recursos humanos',
        descripcion: 'Solución integral para la gestión de Recursos Humanos, optimizando el ciclo de vida del empleado desde el reclutamiento y la selección hasta la gestión de su perfil profesional y capacitaciones.',
        activa: true,
        version: '2.1.0',
        lastUpdate: '2024-07-01',
        lastAudit: '2024-05-10',
        auditor: 'Juan Perez',
        incidents: [],
        clientId: 'RRHH_CLIENT_004',
        code: 'RRHH_CODE_456',
        urlDestino: 'https://rrhh.cesac.mil.do',
        redirectUrl: 'https://rrhh.cesac.mil.do/auth/callback',
        assignedDev: 'Maria Rodriguez',
        backendDev: 'Jorge Diaz',
        frontendDev: 'Kendy Qualey',
        users72h: 120,
        totalUsers: 800,
        technicalDetails: {
            stack: ['React', 'Go (Gin)', 'gRPC'],
            architecture: 'Microservicios',
            database: 'CockroachDB',
            cicd: ['GitLab CI', 'Docker', 'Kubernetes'],
            repository: 'github.com/cesac/rrhh-service',
        },
    },
    {
        id: 'SIARED',
        logo: BookCopy,
        nombre: 'Sistema Automatizado de Recepción de Documentos de Cursos',
        descripcion: 'Sistema Automatizado de Recepción de Documentos de Cursos. Facilita la inscripción, seguimiento y certificación de los cursos de capacitación, automatizando la entrega y validación de la documentación requerida.',
        activa: true,
        version: '1.2.5',
        lastUpdate: '2024-06-15',
        lastAudit: '2024-05-01',
        auditor: 'Ana García',
        incidents: [{ type: 'Menor', count: 5, description: 'Errores de subida de archivos intermitentes.' }],
        clientId: 'SIARED_CLIENT_005',
        code: 'SIARED_CODE_789',
        urlDestino: 'https://siared.cesac.mil.do',
        redirectUrl: 'https://siared.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 75,
        totalUsers: 600,
        technicalDetails: {
            stack: ['Vue.js', 'Node.js (Express)', 'MongoDB'],
            architecture: 'Monolito',
            database: 'MongoDB Atlas',
            cicd: ['GitHub Actions', 'Docker Compose', 'On-Premise Server'],
            repository: 'github.com/cesac/siared-platform',
        },
    },
    {
        id: 'SGAC',
        logo: Mail,
        nombre: 'Sistema de Gestión y Administración de Correspondencia',
        descripcion: 'Herramienta para la gestión y administración de correspondencia interna y externa del CESAC. Digitaliza el flujo de documentos, mejora el seguimiento y reduce los tiempos de respuesta.',
        activa: true,
        version: '4.0.0',
        lastUpdate: '2024-07-25',
        lastAudit: '2024-06-30',
        auditor: 'Juan Perez',
        incidents: [],
        clientId: 'SGAC_CLIENT_006',
        code: 'SGAC_CODE_101',
        urlDestino: 'https://sgac.cesac.mil.do',
        redirectUrl: 'https://sgac.cesac.mil.do/auth/callback',
        assignedDev: 'Maria Rodriguez',
        backendDev: 'Jorge Diaz',
        frontendDev: 'Kendy Qualey',
        users72h: 200,
        totalUsers: 1500,
        technicalDetails: {
            stack: ['Next.js', 'Java (Spring Boot)', 'RabbitMQ'],
            architecture: 'Arquitectura Orientada a Eventos',
            database: 'Oracle DB',
            cicd: ['GitHub Actions', 'Docker', 'OpenShift'],
            repository: 'github.com/cesac/sgac-correspondence',
        },
    },
    {
        id: 'SCC',
        logo: ClipboardCheck,
        nombre: 'Sistema de Control de Calidad',
        descripcion: 'Sistema para la Gestión de Documentos de Control de Calidad. Permite estandarizar procesos, realizar auditorías y dar seguimiento a no conformidades, asegurando el cumplimiento de los más altos estándares de calidad.',
        activa: false,
        version: '1.5.0',
        lastUpdate: '2023-12-01',
        lastAudit: '2023-11-15',
        auditor: 'Ana García',
        incidents: [],
        clientId: 'SCC_CLIENT_007',
        code: 'SCC_CODE_202',
        urlDestino: 'https://scc.cesac.mil.do',
        redirectUrl: 'https://scc.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 0,
        totalUsers: 50,
        technicalDetails: {
            stack: ['Angular', '.NET Core', 'SQL Server'],
            architecture: 'Monolito',
            database: 'Microsoft SQL Server',
            cicd: ['Azure DevOps', 'Docker', 'IIS (On-Premise)'],
            repository: 'github.com/cesac/scc-quality-system',
        },
    },
    {
        id: 'SCF',
        logo: Truck,
        nombre: 'Sistema de Control de Flotas',
        descripcion: 'Plataforma para la administración y monitoreo en tiempo real de la flota vehicular del CESAC. Optimiza rutas, controla el consumo de combustible y gestiona el mantenimiento preventivo para garantizar la operatividad.',
        activa: true,
        version: '2.2.0',
        lastUpdate: '2024-07-18',
        lastAudit: '2024-06-25',
        auditor: 'Juan Perez',
        incidents: [{ type: 'Advertencia', count: 1, description: 'GPS con datos imprecisos en 2 unidades.' }],
        clientId: 'SCF_CLIENT_008',
        code: 'SCF_CODE_303',
        urlDestino: 'https://scf.cesac.mil.do',
        redirectUrl: 'https://scf.cesac.mil.do/auth/callback',
        assignedDev: 'Maria Rodriguez',
        backendDev: 'Jorge Diaz',
        frontendDev: 'Kendy Qualey',
        users72h: 45,
        totalUsers: 300,
        technicalDetails: {
            stack: ['React Native', 'Node.js (NestJS)', 'MQTT'],
            architecture: 'Microservicios (IoT)',
            database: 'TimescaleDB (PostgreSQL)',
            cicd: ['GitHub Actions', 'Docker', 'Kubernetes'],
            repository: 'github.com/cesac/scf-fleet-control',
        },
    },
    {
        id: 'Laboratorio',
        logo: FlaskConical,
        nombre: 'Sistema de Gestión de Muestras para Laboratorio',
        descripcion: 'Controla el flujo de muestras, desde la recepción hasta el análisis y la emisión de resultados, asegurando trazabilidad y fiabilidad en los procesos de laboratorio.',
        activa: false,
        version: '1.0.0',
        lastUpdate: '2023-10-10',
        lastAudit: '2023-09-20',
        auditor: 'Ana García',
        incidents: [],
        clientId: 'LAB_CLIENT_009',
        code: 'LAB_CODE_404',
        urlDestino: 'https://lab.cesac.mil.do',
        redirectUrl: 'https://lab.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 0,
        totalUsers: 30,
        technicalDetails: {
            stack: ['Blazor', '.NET Core', 'SQL Server'],
            architecture: 'Monolito',
            database: 'Microsoft SQL Server',
            cicd: ['Azure DevOps', 'Docker', 'IIS'],
            repository: 'github.com/cesac/lab-sample-manager',
        },
    },
    {
        id: 'SGLS',
        logo: Plane,
        nombre: 'Sistema Gestión Lista Servicios Aeropuertos',
        descripcion: 'Aplicación para la gestión centralizada de la lista de servicios disponibles en los diferentes aeropuertos. Facilita la consulta y actualización de la oferta de servicios para aerolíneas y personal.',
        activa: true,
        version: '1.0.0',
        lastUpdate: '2024-03-01',
        lastAudit: '2024-02-10',
        auditor: 'Ana García',
        incidents: [],
        clientId: 'SGLS_CLIENT_010',
        code: 'SGLS_CODE_505',
        urlDestino: 'https://sgls.cesac.mil.do',
        redirectUrl: 'https://sgls.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 60,
        totalUsers: 400,
        technicalDetails: {
            stack: ['SvelteKit', 'Node.js (Fastify)', 'GraphQL'],
            architecture: 'Microservicios',
            database: 'PostgreSQL',
            cicd: ['GitHub Actions', 'Docker', 'Kubernetes'],
            repository: 'github.com/cesac/sgls-service-list',
        },
    },
    {
        id: 'SGA - CESAC',
        logo: BarChart2,
        nombre: 'Sistema Gestión de Acreditacion (Nube)',
        descripcion: 'La versión cloud del sistema de acreditación, diseñada para ofrecer alta disponibilidad, escalabilidad y acceso seguro desde cualquier ubicación para la gestión de trámites.',
        activa: true,
        version: '1.0.0-Nube',
        lastUpdate: '2024-07-30',
        lastAudit: '2024-07-15',
        auditor: 'Juan Perez',
        incidents: [],
        clientId: 'SGA_NUBE_CLIENT_015',
        code: 'SGA_NUBE_CODE_111',
        urlDestino: 'https://sga-nube.cesac.mil.do',
        redirectUrl: 'https://sga-nube.cesac.mil.do/auth/callback',
        assignedDev: 'Maria Rodriguez',
        backendDev: 'Jorge Diaz',
        frontendDev: 'Kendy Qualey',
        users72h: 300,
        totalUsers: 2000,
        technicalDetails: {
            stack: ['Next.js', 'Go', 'gRPC'],
            architecture: 'Serverless (Cloud Functions)',
            database: 'Firebase Firestore',
            cicd: ['Cloud Build', 'Docker', 'Cloud Run'],
            repository: 'github.com/cesac/sga-nube-accreditation',
        },
    },
    {
        id: 'MA - CESAC',
        logo: Network,
        nombre: 'Modulo de Acreditacion',
        descripcion: 'Módulo principal de Acreditación. Es el núcleo operativo para la gestión de trámites, certificaciones y validaciones de personal y empresas, integrando todos los procesos de seguridad aeroportuaria.',
        activa: true,
        version: '3.1.2',
        lastUpdate: '2024-07-12',
        lastAudit: '2024-06-20',
        auditor: 'Ana García',
        incidents: [{ type: 'Advertencia', count: 2, description: 'Lentitud en la generación de reportes.' }],
        clientId: 'MA_CLIENT_016',
        code: 'MA_CODE_222',
        urlDestino: 'https://ma.cesac.mil.do',
        redirectUrl: 'https://ma.cesac.mil.do/auth/callback',
        assignedDev: 'Carlos Martinez',
        backendDev: 'Luisa Fernandez',
        frontendDev: 'Kendy Qualey',
        users72h: 180,
        totalUsers: 1800,
        technicalDetails: {
            stack: ['JSP (JavaServer Pages)', 'Java Servlets', 'jQuery'],
            architecture: 'Monolito (Legacy)',
            database: 'IBM DB2',
            cicd: ['Jenkins (Manual)', 'WAR file deployment', 'IBM WebSphere'],
            repository: 'github.com/cesac/ma-legacy-module',
        },
    },
];

export const usersData = [
  { 
    id: 1, 
    nombre: 'Administrador Cargos', 
    usuario: 'admincargos', 
    correo: 'josemanuel@cesac.mil.do', 
    telefono: '(809)-000-0000', 
    activo: true,
    rango: 'Asimilado Militar',
    departamento: 'DIRECCIÓN DE TECNOLOGÍA Y COMUNICACIÓN',
    nivelPerfil: 'Master Key',
    appsConcedidas: [initialApps[0], initialApps[1], initialApps[11]],
    ultimosAccesos: [
        { fecha: '2024-08-01', hora: '10:30 AM', app: 'Sistema Gestión Usuario' },
        { fecha: '2024-08-01', hora: '09:15 AM', app: 'Sistema Carnet Unico' },
        { fecha: '2024-07-31', hora: '04:55 PM', app: 'Modulo de Acreditacion' },
    ]
  },
  { 
    id: 2, 
    nombre: 'Administrador Registro Control', 
    usuario: 'adminregistrocontrol', 
    correo: 'henrycodigo@hotmail.com', 
    telefono: '(809)-000-0000', 
    activo: true,
    rango: 'Asimilado Militar',
    departamento: 'DIRECCIÓN DE ACREDITACIÓN Y CERTIFICACIÓN',
    nivelPerfil: 'Administrativo',
    appsConcedidas: [initialApps[0], initialApps[1], initialApps[2], initialApps[3], initialApps[4]],
     ultimosAccesos: [
        { fecha: '2024-08-01', hora: '11:00 AM', app: 'Sistema Gestión Usuario' },
        { fecha: '2024-07-31', hora: '02:00 PM', app: 'Sistema de documentacion de poligrafia' },
        { fecha: '2024-07-31', hora: '11:45 AM', app: 'Sistema de Reclutamiento' },
    ]
  },
  { 
    id: 3, 
    nombre: 'ALEXANDRA BURET RIVAS', 
    usuario: 'a.buret@cesac.mil.do', 
    correo: 'a.buret@cesac.mil.do', 
    telefono: '(849)-258-9975', 
    activo: false,
    rango: 'Asimilado Militar',
    departamento: 'DIRECCIÓN DE ASUNTOS INTERNOS',
    nivelPerfil: 'Estándar',
    appsConcedidas: [initialApps[1]],
    ultimosAccesos: [
        { fecha: '2024-06-15', hora: '03:10 PM', app: 'Sistema Carnet Unico' },
    ]
  },
  { 
    id: 4, 
    nombre: 'Amalia Teresa Burgos', 
    usuario: 'a.burgos', 
    correo: 'a.burgos@cesac.mil.do', 
    telefono: '(829)-903-7937', 
    activo: true,
    rango: 'Sargento Mayor',
    departamento: 'DIRECCIÓN DE TECNOLOGÍA Y COMUNICACIÓN',
    nivelPerfil: 'Avanzado',
    appsConcedidas: [initialApps[0], initialApps[10], initialApps[11]],
     ultimosAccesos: [
        { fecha: '2024-07-29', hora: '08:30 AM', app: 'Sistema Gestión de Acreditacion (Nube)' },
        { fecha: '2024-07-28', hora: '05:20 PM', app: 'Modulo de Acreditacion' },
        { fecha: '2024-07-28', hora: '09:00 AM', app: 'Sistema Gestión Usuario' },
    ]
  },
  { 
    id: 5, 
    nombre: 'Amauris Joel Mercedes Castillo', 
    usuario: 'a.mercedes', 
    correo: 'a.mercedes@cesac.mil.do', 
    telefono: '(809)-545-4552', 
    activo: true,
    rango: 'Cabo',
    departamento: 'Escuela de Seguridad de la Aviación Civil (ESAC)',
    nivelPerfil: 'Estándar',
    appsConcedidas: [initialApps[4]],
     ultimosAccesos: [
        { fecha: '2024-07-30', hora: '02:00 PM', app: 'Sistema Automatizado de Recepción de Documentos de Cursos' },
    ]
  },
  { id: 6, nombre: 'ANA SOFIA PEREZ ASTACIO', usuario: 'a.perez', correo: 'a.perez@cesac.mil.do', telefono: '(809)-000-0000', activo: false, rango: 'Raso', departamento: 'DIRECCIÓN DE TECNOLOGÍA Y COMUNICACIÓN', nivelPerfil: 'Estándar', appsConcedidas: [], ultimosAccesos: [] },
  { id: 7, nombre: 'Angelica Portoreal', usuario: 'a.portorreal', correo: 'a.portorreal@cesac.mil.do', telefono: '(829)-771-1799', activo: true, rango: 'Asimilado Militar', departamento: 'DIRECCIÓN DE ACREDITACIÓN Y CERTIFICACIÓN', nivelPerfil: 'Avanzado', appsConcedidas: [initialApps[0], initialApps[1]], ultimosAccesos: [{ fecha: '2024-07-31', hora: '10:00 AM', app: 'Sistema Carnet Unico' }] },
  { id: 8, nombre: 'BIANNY ROA FLORENTINO', usuario: 'b.roa@cesac.mil.do', correo: 'b.roa@cesac.mil.do', telefono: '(809)-352-7572', activo: true, rango: 'Cabo', departamento: 'DIRECCIÓN DE ASUNTOS INTERNOS', nivelPerfil: 'Estándar', appsConcedidas: [initialApps[2]], ultimosAccesos: [{ fecha: '2024-07-30', hora: '11:00 AM', app: 'Sistema de documentacion de poligrafia' }] },
  { id: 9, nombre: 'Carmen Miguelina Heredia', usuario: 'c.heredia', correo: 'c.heredia@cesac.mil.do', telefono: '(829)-305-7136', activo: false, rango: 'Asimilado Militar', departamento: 'DIRECCIÓN DE TECNOLOGÍA Y COMUNICACIÓN', nivelPerfil: 'Estándar', appsConcedidas: [], ultimosAccesos: [] },
  { id: 10, nombre: 'Carolin Nuñez Sanchez', usuario: 'c.nunez@cesac.mil.do', correo: 'c.nunez@cesac.mil.do', telefono: '(809)-000-0000', activo: true, rango: 'Sargento', departamento: 'DIRECCIÓN DE ACREDITACIÓN Y CERTIFICACIÓN', nivelPerfil: 'Administrativo', appsConcedidas: [initialApps[0], initialApps[1], initialApps[5]], ultimosAccesos: [{ fecha: '2024-08-01', hora: '12:00 PM', app: 'Sistema de Gestión y Administración de Correspondencia' }, { fecha: '2024-07-31', hora: '03:00 PM', app: 'Sistema Gestión Usuario' }] },
];

